name: Terraform run

on: [push]
  # push:
  #   branches:
  #     - 'master'
  # pull_request:
  #   branches:
  #     - 'master'
  # workflow_dispatch:

permissions:
      id-token: write
      contents: read  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Azure login
        uses: azure/login@v2
        with:
            creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3

      - name: Print PWD
        id: set_current_dir
        run: |
          pwd > something.txt
          cat something.txt
          az account show > another.txt
          cat another.txt

      - name: Terraform init
        run: |
          terraform init
          
